apiVersion: v1
kind: PersistentVolume
metadata:
  name: ics-intg-tmp-nfs-pv
  labels:
    type: ics-intg-temp-nfs-pv
spec:
  storageClassName: persistent-nfs-storage
  claimRef:
    name: ics-intg-tmp-nfs-pv-claim
    namespace: ics-intg
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: netapp.haasgroupintl.com
    path: /ics_dev_temp
