apiVersion: v1
kind: PersistentVolume
metadata:
  name: ics-stg-msds-nfs-pv
  labels:
    type: ics-stg-msds-nfs-pv
spec:
  storageClassName: persistent-nfs-storage
  claimRef:
    name: ics-stg-msds-nfs-pv-claim
    namespace: ics-stage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: netapp.haasgroupintl.com
    path: /ics_stg_msds
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ics-stg-receiptimages-nfs-pv
  labels:
    type: ics-stg-receiptimages-nfs-pv
spec:
  storageClassName: persistent-nfs-storage
  claimRef:
    name: ics-stg-receiptimages-nfs-pv-claim
    namespace: ics-stage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: netapp.haasgroupintl.com
    path: /ics_stg_receiptimages
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ics-stg-docimages-nfs-pv
  labels:
    type: ics-stg-docimages-nfs-pv
spec:
  storageClassName: persistent-nfs-storage
  claimRef:
    name: ics-stg-docimages-nfs-pv-claim
    namespace: ics-stage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: netapp.haasgroupintl.com
    path: /ics_stg_docimages
