apiVersion: v1
kind: Service
metadata:
  name: delegate-service
  namespace: ics-devops
spec:
  type: ClusterIP
  selector:
    harness.io/name: ics-harness-delegate-prod
  ports:
    - port: 8080

